# Topics
depth_topic: "/camera/depth/image_rect_raw"

# IDR
baseline: 95 # mm
hres: 640    # horizontal resolution (640x480)
hfov: 90     # 90 +- 1 degrees
vfov: 65     # 65 +- 1 degree
dfov: 89     # 89 +- 1 degrees

