# Topics
depth_topic: "/camera/depth/image_rect_raw"

# IDR
baseline: 95         # mm
hfov: 90             # 90 +- 1 degrees
vfov: 65             # 65 +- 1 degree
dfov: 89             # 89 +- 1 degrees
adjacent_padding: 25 # Pixels

# Testing Purposes
test_distance: 1000 # mm

